### ISSUE TITLE
Binaries for macOS based on your repo?

### ISSUE THREAD

**Issue by fdanapfel** [Kreeblah/d2x-xl#1]
Hello,

I'm currently using the official d2x-xl binary for macOS from http://www.descent2.de which is a bit dated. The main issue I currently have is that it seems to be built against a very old version of SDL which doesn't#t support the PS4 DualShock controller which is finally fully supported with macOs Catalina.

While searching for a possibility of getting a more recent version of d2x-xl for macOS which is build against a current version of SDLI discovered this GitHub repo, and since it looks like you  have made some patches to the code related to macOS, I was wondering if ou have been able to compile this code with a current version of SDL for macOS?

If yes, would you be willing to share the binary, or at least provide some guidance on how to build the current version for macOS using your repo?

**Comment by Kreeblah** [comment]
Unfortunately, it's still a work in progress, and doesn't build quite yet.  My hope is to get it building with cmake and the generated makefile, since I've found Xcode projects to be pretty fragile with cross-platform applications.  However, I'm going to need to port over whatever the Xcode project is doing for that to happen, which I haven't done yet.  Right now, building with cmake fails because it tries to use some Linux headers for the networking portion instead of just sticking with SDL_net.

Unfortunately, the Xcode version is also not currently building for me, and I've had issues figuring out why.  It fails to find a header (cmath) that's included with Xcode, and I haven't had a whole lot of luck figuring out what's misconfigured.

**Comment by fdanapfel** [comment]
Thanks for the quick reply. Hope you can get those issues resolved.

I wish I could help in any way, but unfortunately my knowledge of using Xcode and building applications for macOS  is close to zero :(
